apiVersion: apps/v1
kind: Deployment
metadata:
  name: edufya-llm-api
  labels:
    app: edufya-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edufya-llm
  template:
    metadata:
      labels:
        app: edufya-llm
    spec:
      containers:
      - name: api
        image: gauravpatel1202/edufya-llm-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: edufya-llm-service
spec:
  selector:
    app: edufya-llm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
